execute:
	python3 simple_cnn.py

test:
	# pytest -v test_loss.py -k 'test_wrong_dimensions_raise_AssertionError or test_custom_returns_torch_float or test_custom_1dipole_1sample or test_custom_1dipole_2samples'
	pytest test_loss.py
